"""
    APhoS

    This is Amateur Photometric Survey (APhoS) Application Programming Interface.   # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Contact: pavelkinc230@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest
import responses
from pprint import pprint

from aphos_openapi.api_client import ApiClient

import aphos_openapi

from aphos_openapi.api.catalog_api import CatalogApi  # noqa: E501


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_catalogs(self):
        """Test case for get_catalogs

        Find all catalogs  # noqa: E501
        """
        #pprint(self.api.get_catalogs_endpoint())
        result = self.api.get_catalogs()
        pprint(result)


if __name__ == '__main__':
    unittest.main()
