"""
    APhoS

    This is Amateur Photometric Survey (APhoS) Application Programming Interface.   # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Contact: pavelkinc230@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest


from aphos_openapi.api.catalog_api import CatalogApi  # noqa: E501


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs
    basic testing of endpoints"""

    def setUp(self):
        self.api = CatalogApi()  # noqa: E501

    def tearDown(self):
        del self.api

    def test_get_catalogs(self):
        """Test case for get_catalogs

        Find all catalogs  # noqa: E501
        """
        #pprint(self.api.get_catalogs_endpoint())
        result = self.api.get_catalogs()
        assert len(result) >= 3
        assert "UCAC4" in result


if __name__ == '__main__':
    unittest.main()
