# flake8: noqa

"""
    APhoS

    This is Amateur Photometric Survey (APhoS) Application Programming Interface.   # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Contact: pavelkinc230@gmail.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from aphos_openapi.api_client import ApiClient

# import Configurat
from aphos_openapi.configuration import Configuration

# import exceptions
from aphos_openapi.exceptions import OpenApiException
from aphos_openapi.exceptions import ApiAttributeError
from aphos_openapi.exceptions import ApiTypeError
from aphos_openapi.exceptions import ApiValueError
from aphos_openapi.exceptions import ApiKeyError
from aphos_openapi.exceptions import ApiException
